### ISSUE TITLE
No Extension Settings Menu in 5.00 (475603)

### ISSUE THREAD

**Issue by leoric** [bvbohnen/x4-projects#12]
clean install of latest versions from here

sn_mod_support_apis
sn_extra_game_options
sn_hotkey_collection
sn_interact_collection

and no menu

https://imgur.com/a/gjs9iqE

tried to remove all files from Documents\Egosoft and restart - no changes
https://controlc.com/fd3ec330

**Comment by leoric** [comment]
I kinda know how to use extensions, there are about fifty of them in my game, this was just a clean install to test is it is conflicting with something. steam workshop version works fine, but jumping through all the loops to get it for non-steam game is exhausting

**Comment by CinemaGame** [comment]
I have a similar problem in the non-Steam version of "X4", I even deleted all the other extensions, but the menu in the game itself did not appear. I've been desperate for 3 days trying to fix this "clunker". Even in YouTube there are no guides for installing these mods /fixing this problem, since no one has encountered it and there are no difficulties with installation:(

**Comment by bvbohnen** [comment]
There generally shouldn't be differences between steam and non-steam x4, unless the steam workshop is changing extension enables on each game startup.

For debugging, an early possible point of failure would be in the lua loader. Editing the subst01.dat file to uncomment "--DebugError" lines to "  DebugError" (use spaces to keep the file size unchanged) will show in the debuglog if mod lua files are loading properly.

**Comment by chantling** [comment]
I was having the same issue in v6, and it turned out the problem was that I had renamed this mod's folder to move it to the end of the extension list in my file manager.  I've been rebuilding my mod list for v6 and I constantly move all mods to another folder while I test and fix new mods, and it was a pain to keep finding sn_mod_support_apis and x4-mod-ui-extensions in the list to deselect them each time.  I forgot that there are certain mods that won't work if their folder gets renamed.  This may be the issue with the posters above.  A bit belated of a fix, if so, but may help in the future.
